# dockerfiles/Dockerfile.node
FROM node-nvm-base:latest

ARG NODE_VERSION
ARG NPM_VERSION
ARG INSTALL_PM2=false

ENV NVM_DIR=/usr/local/.nvm

# Install Node and NPM
RUN source $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    npm install -g npm@$NPM_VERSION

# RUN if [ $INSTALL_PM2=true ]; then \
#       npm install -g pm2@latest; \
#     fi

ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

CMD ["sh"]