# dockerfiles/Dockerfile.node
FROM nvm-node-base:latest

ARG NODE_VERSION
ARG NPM_VERSION

ENV NVM_DIR=/root/.nvm

# Install Node and NPM
RUN bash -c "source $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    npm install -g npm@$NPM_VERSION"

# Set runtime PATH
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

SHELL ["/bin/bash", "-c"]