FROM debian:bookworm-slim

ENV NVM_DIR=/usr/local/.nvm
ENV PROFILE=/root/.bashrc

RUN mkdir $NVM_DIR

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

ENV PATH="$NVM_DIR/versions/node/default/bin:$PATH"
SHELL ["/bin/bash", "-c"]
